from pydantic import BaseModel, ConfigDict, Field

class Deal(BaseModel):
    """
    Merchant-authorized transaction terms.

    Unlike PurchaseProposal, these values are generated by AMPP's
    deterministic policy engine.
    """

    model_config = ConfigDict(extra="forbid")
    transaction_id: str
    merchant_id: str
    sku: str
    quantity: int = Field(gt=0)
    base_unit_price: int = Field(gt=0)
    approved_unit_price: int = Field(gt=0)
    total_amount: int = Field(gt=0)

    currency: str = Field(
        min_length=3,
        max_length=3,
    )

    hold_token: str
    expires_at: int = Field(gt=0)

    state: str = Field(
        description="Current transaction state.",
    )