from pydantic import BaseModel, ConfigDict, Field

class PaymentChallenge(BaseModel):
    """
    HTTP 402 payment challenge generated by AMPP.
    """
    model_config = ConfigDict(extra="forbid")
    protocol: str = "x402"
    version: str = "1"
    payment_required: bool = True
    amount: int = Field(gt=0)

    currency: str = Field(
        min_length=3,
        max_length=3,
    )

    transaction_id: str
    hold_token: str
    expires_at: int = Field(gt=0)
    settlement_rail: str

class SettlementRequest(BaseModel):
    """
    Agent response to a payment challenge.
    """
    model_config = ConfigDict(extra="forbid")
    transaction_id: str
    hold_token: str

    nonce: str = Field(
        min_length=16,
        description="Fresh nonce for replay protection.",
    )


class SettlementResult(BaseModel):
    """
    Result returned after successful settlement.
    """
    model_config = ConfigDict(extra="forbid")
    transaction_id: str
    payment_id: str
    status: str
    amount: int = Field(gt=0)
    currency: str
    receipt_digest: str